version: '3.9'

services:
  updateip:
    image: ${DOCKER_APP_IMAGE_NAME}:${DOCKER_APP_IMAGE_TAG}
    container_name: update-ip
    restart: unless-stopped
    environment:
      - intervalTime=60
      - domain=yamiannephilim.com
      - loginToken=YnRAXwL_Ob54ESmxScSeVmM-TKHN3yQK1oeej8_d
      - subDomains=yamiannephilim.com,true;ssh.yamiannephilim.com,false
    deploy:
      resources:
        limits:
          memory: 0.5g
          cpus: '0.5'
