services:
  update-ip:
    image: ${DOCKER_APP_IMAGE_NAME}:${DOCKER_APP_IMAGE_TAG}
    container_name: update-ip
    environment:
      - domain=phuongdoan.name.vn
      - subDomains=phuongdoan.name.vn
      - loginToken=FGHDFEFGH43DFGDG
      - intervalTime=60
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: always
